main:
  - identifier: home
    name: Bio
    pageRef: /
    weight: 10
  - identifier: news
    name: News
    url: /#news
    weight: 11
  - identifier: experience
    name: Experience
    pageRef: /experience
    weight: 20
  - identifier: projects
    name: Projects
    pageRef: /projects
    weight: 30
